print("\nWorkshop 1 Part-1")
print("=================\n")
print("I'm displaying this using the 'printf' stdio\n(standard input output) library function!\n")
print("Dear teacher,\n")
print("    I promise I will work hard from this day onward.")
print("    I acknowledge that practice is extremely important,")
print("    so I will do all workshops, quizzes, and assignments.\n")
print("Sincerely,\n")
print("Selin Uluca ")
print("Student ID# 22220030046 \n")
