print("\nWorkshop 1 Part-2")
print("====================")
print("\nUsing tab specifiers...")
print("<t>\tTab-1 <t>\tTab-2 <t>\tTab-3")
print("<t>\t----- <t>\t===== <t>\t-----")
print("\n\\ this is a back-slash character! ")
print("% this is a percent sign character! ")
print("\" this is a double-quote character! ")
print("\nMy favorite quotes are:")
print("1.<t>\t""Skill is only developed by hours and hours of work.""")
print("<6t>\t\t\t\t\t\t-Usain Bolt\n")
print("2.<t>\t""It's not about having time. It's about making time.""")
print("<6t>\t\t\t\t\t\t-unknown\n")
print("3.<t>\t""All of us do not have equal talent. But, all of us\n<t>\thave an equal opportunity to develop our talents.""")
print("<6t>\t\t\t\t\t\t-A.P.J Abdul Kalam\n")
